development:
  adapter: postgresql
  encoding: unicode
  database: rails4_action_controller_live_with_google_maps_sample_development
  pool: 5
  username: rails4_action_controller_live_with_google_maps_sample
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rails4_action_controller_live_with_google_maps_sample_test
  pool: 5
  username: rails4_action_controller_live_with_google_maps_sample
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: rails4_action_controller_live_with_google_maps_sample_production
  pool: 5
  username: rails4_action_controller_live_with_google_maps_sample
  password:
  host: localhost

